import Footer5 from "@/components/footers/Footer5";
import Header5 from "@/components/headers/Header5";
import { ligitNavigationMultipage } from "@/data/menu";
import ParallaxContainer from "@/components/common/ParallaxContainer";

export const metadata = {
  title: "Disclaimer - Ligit",
  description: "Disclaimer for Ligit - Your Intelligent Legal AI Assistant",
};

export default function Disclaimer() {
  return (
    <>
      <div className="theme-elegant">
        <div className="dark-mode">
          <div className="page bg-dark-1" id="top">
            <nav className="main-nav dark dark-mode transparent stick-fixed wow-menubar">
              <Header5 links={ligitNavigationMultipage} />
            </nav>
            <main id="main">
              <ParallaxContainer
                className="page-section bg-dark-alpha-30 light-content z-index-1"
                style={{
                  backgroundImage:
                    "url(/assets/images/demo-elegant/scales_of_justice_hero.jpg)",
                  backgroundPosition: "center center",
                  backgroundSize: "cover",
                }}
              >
                <div className="container position-relative pt-50">
                  <div className="text-center">
                    <h1 className="hs-title-1 mb-20">
                      <span className="wow charsAnimIn" data-splitting="chars">
                        Disclaimer
                      </span>
                    </h1>
                  </div>
                </div>
              </ParallaxContainer>

              <section className="page-section bg-dark-1 light-content">
                <div className="container relative">
                  <div className="row">
                    <div className="col-lg-10 offset-lg-1">
                      <div className="section-text" style={{ fontSize: '90%' }}>
                        <h2 className="section-title-small mb-30">Disclaimer</h2>
                        <p className="text-gray mb-30">Effective Date: July 13, 2025</p>
                        
                        <p className="mb-30">
                          This Disclaimer ("Disclaimer") governs the use of Ligit (the "Platform"), an AI-based legal support tool developed and operated by Inflekt Core Private Limited ("Company", "we", "us", or "our").
                        </p>
                        <p className="mb-30">
                          By accessing or using the Platform, including but not limited to its services related to legal research, document translation, legal chronology generation, drafting, and review (collectively, the "Services"), you ("you" or "user") agree to this Disclaimer in full. If you do not agree with any part of this Disclaimer, please do not use the Platform.
                        </p>

                        <h3 className="mb-20">1. No Legal Advice</h3>
                        <p className="mb-20">
                          The Platform is designed to assist legal professionals by automating routine legal support tasks using AI and language models. However, Ligit does not provide legal advice, legal opinion, or representation of any kind.
                        </p>
                        <p className="mb-20">The information, documents, summaries, translations, timelines, drafts, or outputs generated by Ligit:</p>
                        <ul className="mb-30">
                          <li className="mb-10">Do not constitute legal advice, and</li>
                          <li className="mb-10">Should not be relied upon as a substitute for advice from a qualified legal practitioner, and</li>
                          <li className="mb-10">Are not intended to create an attorney-client relationship between you and Inflekt Core Private Limited or Ligit.</li>
                        </ul>
                        <p className="mb-30">
                          You are solely responsible for reviewing, validating, and interpreting the outputs provided by the Platform. If you are unsure about any legal issue or interpretation, you should consult a qualified lawyer.
                        </p>

                        <h3 className="mb-20">2. AI-Generated Content</h3>
                        <p className="mb-20">
                          Ligit uses AI models and automation tools to process user inputs and generate responses, documents, or summaries. While we strive for accuracy and relevance:
                        </p>
                        <ul className="mb-30">
                          <li className="mb-10">The outputs are generated based on probabilistic AI reasoning, not human judgment or legal analysis.</li>
                          <li className="mb-10">The results may occasionally contain inaccuracies, outdated references, contextual errors, or omissions.</li>
                          <li className="mb-10">Legal content may not reflect jurisdiction-specific nuances, recent case law, or current regulatory changes.</li>
                        </ul>
                        <p className="mb-30">
                          We make no warranties or guarantees about the completeness, accuracy, or reliability of the AI-generated content. All results are provided "as is" and "as available."
                        </p>

                        <h3 className="mb-20">3. No Guarantees of Outcome</h3>
                        <p className="mb-20">The use of the Platform does not guarantee:</p>
                        <ul className="mb-30">
                          <li className="mb-10">A specific legal outcome in any matter, case, or transaction,</li>
                          <li className="mb-10">Compliance with legal deadlines, rules, or formats,</li>
                          <li className="mb-10">The enforceability or validity of documents generated using the Platform.</li>
                        </ul>
                        <p className="mb-30">
                          Any legal or procedural risks associated with the use of the Platform are solely borne by you. Ligit is intended to be a productivity-enhancing tool, not a replacement for human legal analysis or review.
                        </p>

                        <h3 className="mb-20">4. User Responsibility</h3>
                        <p className="mb-20">You are solely responsible for:</p>
                        <ul className="mb-30">
                          <li className="mb-10">The accuracy and legality of the content you upload or input into the Platform,</li>
                          <li className="mb-10">Reviewing and verifying all outputs before relying on them for legal, regulatory, or commercial purposes, and</li>
                          <li className="mb-10">Ensuring compliance with all applicable laws, rules, regulations, and ethical obligations that govern your practice or organization.</li>
                        </ul>
                        <p className="mb-30">
                          We are not liable for any consequences, legal or otherwise, arising from your use of the Services or your reliance on any AI-generated output.
                        </p>

                        <h3 className="mb-20">5. Third-Party Integrations</h3>
                        <p className="mb-30">
                          Ligit may integrate or interact with third-party tools or platforms (such as AI APIs, payment gateways, or analytics tools). While we choose reputable vendors, we do not control or guarantee the performance of these third-party services. Your use of such services is subject to their respective terms and privacy policies.
                        </p>

                        <h3 className="mb-20">6. Limitation of Liability</h3>
                        <p className="mb-20">
                          To the fullest extent permitted by applicable law, Inflekt Core Private Limited disclaims all liability for any direct, indirect, incidental, consequential, or special damages arising out of or in connection with:
                        </p>
                        <ul className="mb-30">
                          <li className="mb-10">Your access to or use of the Platform,</li>
                          <li className="mb-10">Reliance on any output generated through the Services,</li>
                          <li className="mb-10">Errors, omissions, delays, or inaccuracies in results,</li>
                          <li className="mb-10">Technical failures, downtime, or data loss,</li>
                          <li className="mb-10">Unauthorized access to or alteration of your transmissions or data.</li>
                        </ul>
                        <p className="mb-30">
                          Use of the Platform is at your own risk. If you are dissatisfied with the Platform, your sole remedy is to discontinue use.
                        </p>

                        <h3 className="mb-20">7. Jurisdiction-Specific Disclaimers</h3>
                        <p className="mb-30">
                          Ligit is intended for use in India by legal professionals and organizations operating under Indian law. Users from other jurisdictions are responsible for ensuring that use of the Platform complies with local laws and regulations.
                        </p>

                        <h3 className="mb-20">8. Updates to This Disclaimer</h3>
                        <p className="mb-30">
                          We may revise this Disclaimer from time to time. Any changes will be effective upon posting on the Platform. Continued use of the Services after any changes constitutes your acceptance of the revised Disclaimer.
                        </p>

                        <h3 className="mb-20">9. Contact Us</h3>
                        <p className="mb-30">
                          If you have any questions about this Disclaimer or the use of the Ligit Platform, please contact:
                        </p>
                        <p className="mb-30">
                          📧 support@ligit.com
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
            </main>
            <footer className="bg-dark-2 light-content footer z-index-1 position-relative">
              <Footer5 />
            </footer>
          </div>
        </div>
      </div>
    </>
  );
}